trigger:
  - master
variables:
#Container registry Services Connection established during pipeline creation
  dockerRegistryServiceConnection: 'isaggio-tech-registry'
  imageRepository: 'maven-hello-world'
  containerRegistry: 'isaggio.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Maven_Build
    displayName: Maven Build
    jobs:
      - job: Build
        displayName: Maven Build
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.8'
              jdkArchitectureOption: 'x64'
              publishJUnitResults: true
              testResultsFiles: "**/surefire-reports/TEST-*.xml"
          - publish: $(System.DefaultWorkingDirectory)/target
            artifact: target

  - stage: Image_Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build and push Docker image
        steps:
          - download: current
            artifact: target
          - task: CmdLine@2
            inputs:
              script: |
                echo "Hello-Inside-CommandLine"
                pwd
                ls -lsrt
                id
          - task: Docker@2
            displayName: Push the Docker image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
                latest
#              arguments: '--build-arg ubuntu_version=$(Pipeline.Workspace)/jars/'









